services:
  scraper:
    build: .
    image: amazon-scraper:test
    volumes:
      - ./output:/app/output
      - ./logs:/app/logs
    # Comando padrão para testes (override com 'up --build scraper pytest')
    entrypoint: []
    command: pytest --maxfail=1 --disable-warnings -q